SELECT * FROM MOVIES;

SELECT FIRST_NAME, LAST_NAME FROM ACTORS;

SELECT TITLE FROM SERIES;

SELECT FIRST_NAME, LAST_NAME, RATING FROM ACTORS
WHERE RATING > 7.5;

SELECT TITLE, RATING, AWARDS FROM MOVIES
WHERE RATING> 7.5 AND AWARDS>2;

SELECT TITLE, RATING FROM MOVIES
ORDER BY RATING ASC;

SELECT TITLE, RATING FROM MOVIES
WHERE TITLE LIKE '%Toy Story%';

SELECT * FROM ACTORS
WHERE FIRST_NAME LIKE 'Sam%';

SELECT TITLE, CREATED_AT FROM MOVIES
WHERE CREATED_AT BETWEEN '2004-01-01' AND '2008-12-31'