SELECT ID AS ID_SERIE, CREATED_AT AS CREACION, UPDATED_AT AS ACTUALIZACION, TITLE AS TITULO, RELEASE_DATE AS FECHA_PUBLICACION, END_DATE AS FECHA_FIN, GENRE_ID AS ID_GENERO FROM series;

SELECT TITLE, RATING, RELEASE_DATE FROM MOVIES
WHERE RATING>3 AND AWARDS>1 AND (RELEASE_DATE BETWEEN '1988-01-01' AND '2009-12-31')
ORDER BY RATING DESC;

SELECT TITLE, RATING, RELEASE_DATE FROM MOVIES
WHERE RATING>3 AND AWARDS>1 AND (RELEASE_DATE BETWEEN '1988-01-01' AND '2009-12-31')
ORDER BY RATING DESC
LIMIT 3
OFFSET 10;


